- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/CredentialOffer/GrantTypes/PreAuthorizedCode.cs
This PR adds the UserPinLength Property to the PreAuthorizedCode flow according to https://github.com/openid/OpenID4VCI/issues/10#issuecomment-1749113681 
- add UserPinLength Property
> Change UserPin to TransactionCode

- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/Authorization/TokenRequest.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/CredentialOffer/GrantTypes/PreAuthorizedCode.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/DefaultOid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/IOid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpHaipClient.cs
- src/Hyperledger.Aries/Features/Pex/Models/Descriptor.cs
- src/Hyperledger.Aries/Features/Pex/Models/DescriptorMap.cs
**Short description of what this resolves:**
This PR changes the user_pin to tx_code and adds minor HAIP compatibility changes
**Changes proposed in this pull request:**
- In PreAuthorizedCode replace user_pin with tx_code
- Change TokenRequest to tx_code
- fix VpToken
- fix fix path_nested
> Change user pin to tx code

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/OidPresentationRecord.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/IOid4VpRecordService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpRecordService.cs
- src/Hyperledger.Aries/Features/SdJwt/Models/Records/SdJwtRecord.cs
Added name to OidPresentationRecord
- See description
> adjust OidPresentationRecord

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpClientService.cs
- src/Hyperledger.Aries/Features/SdJwt/Services/SdJwtVcHolderService/DefaultSdJwtVcHolderService.cs
- src/Hyperledger.Aries/Hyperledger.Aries.csproj
This PR fixes two bugs in the Oid4Vp flow:
- Now the http response of the verifier must not include a redirect_uri
- The Verifier can now request Sd-Jwts without requesting any Disclosures
- Oid4VpClientService
- DefaultSdJwtVcHolderService
> Fix oid4vp flow

- .github/workflows/publish-nuget.yaml
This PR fixes the authorization job in the pipeline
- publish-nuget.yaml
> Fix pipeline

- .github/workflows/publish-nuget.yaml
This PR reverts the pipeline changes since the pull_request_target event doesn't allow builds in the PRs context.
- publish-nuget.yaml
> revert pipeline

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpHaipClient.cs
This PR resets the HEADERS within the VP flow before each http request.
> reset headers before each request

- MAINTAINERS.md
This PR adds JoTiTi to the list of Maintainers.
- MAINTAINERS.md
> Update List of Maintainers

- Directory.Build.props
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/Metadata/Issuer/OidIssuerMetadata.cs
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Samples.cs
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Vci/IssuerMetadataTests.cs
Added tests for serialization of issuer metadata.
> Add issuer metadata tests

- .github/workflows/publish-nuget.yaml
This PR fixes the pipeline and adds apt-get update before apt-get install is executed.
> add apt-get update before install

- src/Hyperledger.Aries/Features/SdJwt/Models/Records/SdJwtRecord.cs
This PR adds an Order Property to the Sd-Jwt Record according to the Order property in the CredentialMetadata.
> add claim order property

- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Exceptions/Oid4VciInvalidGrantException.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/Oid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Exceptions/Oid4VpNoCredentialCandidateException.cs
- src/Hyperledger.Aries/Features/SdJwt/Services/SdJwtVcHolderService/DefaultSdJwtVcHolderService.cs
- test/Hyperledger.Aries.Tests/Features/SdJwt/SdJwtVcHolderTests.cs
This PR adds two Exceptions:
- When no credential candidates are found during the Oid4Vp flow
- When the tx_code within the Oid4Vci flow is not entered correctly.
> Introduce more specific exceptions

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpClientService.cs
- test/Hyperledger.Aries.Tests/Integration/Oid4VpClientServiceTests.cs
This PR fixes a bug where an invalid json in the VP response from the verifier leads to an exception instead of returning null.
> add try catch

- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/Authorization/TokenRequest.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/CredentialOffer/GrantTypes/PreAuthorizedCode.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/IOid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/Oid4VciClientService.cs
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Vci/Services/Oid4VciClientServiceTests.cs
This PR reverts the changes to support user_pin and tx_code simultaneously.
> Revert "Support user pin and tx code simultaneously"

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpHaipClient.cs
This PR fixes the descriptor map in the vp_flow when presenting multiple credentials.
> fix descriptor map

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/AuthorizationRequest.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/ClientMetadata.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/OidPresentationRecord.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/IOid4VpRecordService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpHaipClient.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpRecordService.cs
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Vp/Services/Oid4VpHaipClientTests.cs
This PR adds client client_metadata and client_metadata_uri capabilities.
> Implement client metadata

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Extensions/JwtSecurityTokenExtensions.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/RequestObject.cs
This PR adds support for RSA signatures within the x509 certificate for verifier authentication
> add rsa verification

- src/WalletFramework.Oid4Vc/Oid4Vp/Extensions/X509CertificateExtensions.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/RequestObject.cs
This PR allows wildcard SAN DNS Names during x509 validation in Oid4Vp flow.
> add wildcard capabilities

- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- This PR fixes the creation of the auth server metadata url
> fix creation of auth server metadata url

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientMetadata.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/Services/Oid4VpHaipClientTests.cs
> extend client metadata

- src/WalletFramework.Core/Cryptography/Abstractions/IKeyStore.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/Implementations/TokenService.cs
Use ephemeral keys for the DPoP header
- Add ephemeral key creation to keystore interface
> add ephemeral key for dpop

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
- Allow direct_post.jwt as response_mode in Authorization Request
> Update Response Mode

- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtSignerService.cs
- Do not add value to kb-jwt payload if null
> Fix kb-jwt payload

- src/WalletFramework.Core/Base64Url/Base64UrlString.cs
- src/WalletFramework.Core/Cryptography/Models/PublicKey.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/DPop/Implementations/DPopHttpClient.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtSigner.cs
Adds AsByteArray property to Base64UrlString
> Adjust Base64UrlString

- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/PresentationDefinition.cs
- This PR add the JSON Property to the purpose property.
> add json property purpose

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- This PR fixes the Client Attestation and adds the appropriate HEADERS to the http client.
> Fix Client Attestation

- src/WalletFramework.Oid4Vc/Oid4Vci/CredRequest/Implementations/CredentialRequestService.cs
- use non-permanent key in ad hoc issuance flow
> use non permanent key in ad-hoc issuance flow

- global.json
- src/WalletFramework.Core.Tests/Validation/ApplyTests.cs
- src/WalletFramework.Core.Tests/Validation/ValidationTests.cs
- src/WalletFramework.Core.Tests/WalletFramework.Core.Tests.csproj
- src/WalletFramework.sln
Add tests for the Validation<T>. Also allows to roll to .NET 8
> add validation tests

- MAINTAINERS.md
> add maintainer to wallet-framework-dotnet

- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/InputDescriptor.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/PexService.cs
- test/WalletFramework.Oid4Vc.Tests/PresentationExchange/Services/PexServiceTests.cs
This PR allows enum filters in InputDescriptors
> add support for enum filter

- src/WalletFramework.Oid4Vc/CredentialSet/CredentialSetService.cs
- src/WalletFramework.Oid4Vc/CredentialSet/ICredentialSetService.cs
- src/WalletFramework.Oid4Vc/CredentialSet/Models/CredentialSetRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/IOid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
- This PR fixes the ExpiresAt field in the CredentialSetRecord 
- This PR adds the IssuedAt and NotBefore fields to the CredentialSetRecord
- Adds methods to handle the CredentialSetStates
> Add Credential validity logic

- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
This PR adds the new Status List Nesting.
> Add new Status List Nesting

- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
This PR fixes the nbf value extraction in for Sd-Jwt Records
> fix the nfb extraction in sd-jwt

- src/WalletFramework.IsoProximity/WalletFramework.IsoProximity.csproj
- src/WalletFramework.Oid4Vc/Oid4Vci/CredRequest/Implementations/CredentialRequestService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Errors/InvalidRequestError.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequestCancellation.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/PresentationCandidate.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/SelectedCredential.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/InputDescriptor.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/PresentationDefinition.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/AuthorizationRequestService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionData.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataArray.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataHash.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataProperties.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataType.cs
- src/WalletFramework.Oid4Vc/Payment/PaymentTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/DocumentDigest.cs
- src/WalletFramework.Oid4Vc/Qes/DocumentDigestLabel.cs
- src/WalletFramework.Oid4Vc/Qes/InputDescriptorTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/QesAuthorizationTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/UC5QesTransactionData.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/ISdJwtSigner.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/ISdJwtVcHolderService.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtSigner.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtVcHolderService.cs
- test/WalletFramework.Integration.Tests/WalletFramework.Integration.Tests/Oid4Vp/Oid4VpClientServiceTests.cs
- test/WalletFramework.Oid4Vc.Tests/Payment/PaymentTests.cs
- test/WalletFramework.SdJwtVc.Tests/SdJwtVcHolderServiceTests.cs
Implements transaction data for qualified electronic signatures (QES)
- Adds transaction data OneOf type
- Adds qes tx data type
-
**Fixes**: #
> qes transaction data

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/Errors/InvalidTransactionDataError.cs
- Adds optional presentation candidates to txDataError
- See description
**Fixes**: #
> Adjust txdata error

- src/WalletFramework.Oid4Vc/Oid4Vci/CredConfiguration/Models/SdJwt/SdJwtConfiguration.cs
- src/WalletFramework.SdJwtVc/Models/Credential/Attributes/ClaimMetadata.cs
- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/AuthFlow/AuthFlowSessionRecordTests.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/AuthFlow/Samples/AuthFlowSamples.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/CredConfiguration/SdJwt/Samples/SdJwtConfigurationSample.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/Issuer/IssuerMetadataTests.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/Issuer/Samples/IssuerMetadataSample.cs
This PR adds support for the ClaimPath structure introduced in Vci Draft15 but stays backwards compatible with VCI Draft14 and below.
> add VCI Draft15 claimPath structure to IssuerMetadata

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
Fixed small issue where uc5 txdata was confused with normal txdata.
> fix uc5 txdata

- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/Implementations/AuthorizationResponseEncryptionService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Jwk/JwkSet.cs
This PR fixes the selection of JWKs for the Encrypted Authorization Response.
> fix JWK selection for Encrypted Authorization Response

- src/WalletFramework.Oid4Vc/Dcql/Models/CredentialQuery.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
- src/WalletFramework.Oid4Vc/RelyingPartyAuthentication/RegistrationCertificate/OverAskingValidationResult.cs
- src/WalletFramework.Oid4Vc/RelyingPartyAuthentication/RpAuthResult.cs
- src/WalletFramework.Oid4Vc/RelyingPartyAuthentication/RpTrustLevel.cs
- test/WalletFramework.Oid4Vc.Tests/RelyingPartyAuthentication/RPAuthenticationTests.cs
This PR makes the enum for the RP Authentication Trust Result more expressive.
> Make TrustResult enum more expressive

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/PresentationCandidate.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/SelectedCredential.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/InputDescriptor.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionData.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataArray.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataProperties.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataType.cs
- src/WalletFramework.Oid4Vc/Payment/PaymentTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/Authorization/DocumentDigest.cs
- src/WalletFramework.Oid4Vc/Qes/Authorization/DocumentDigestLabel.cs
- src/WalletFramework.Oid4Vc/Qes/Authorization/InputDescriptorTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/Authorization/QesAuthorizationTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/Authorization/UC5QesTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/CertCreation/QCertCreationTransactionData.cs
- src/WalletFramework.Oid4Vc/Qes/CertCreation/TermsConditionsUri.cs
- src/WalletFramework.Oid4Vc/WalletFramework.Oid4Vc.csproj
- test/WalletFramework.Integration.Tests/WalletFramework.Integration.Tests/Oid4Vp/Oid4VpClientServiceTests.cs
- test/WalletFramework.Oid4Vc.Tests/QCertCreation/QCertCreationTests.cs
- test/WalletFramework.Oid4Vc.Tests/QCertCreation/Samples/QCertTransactionDataSamples.cs
This PR adds support for transaction data type "qcert_creation_acceptance"
-
-
-
**Fixes**: #
> add support for qcert_creation_acceptance transaction data

- src/WalletFramework.Oid4Vc/Oid4Vci/CredRequest/Implementations/CredentialRequestService.cs
Decrease the MaxBatchCount from 20 to 10.
> Decrease MaxBatchSize

- src/WalletFramework.Oid4Vc/ClientAttestation/ClientAttestationDetails.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/ClientAttestationPopDetails.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/ClientAttestationService.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/HttpClientExtensions.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/IClientAttestationService.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/WalletInstanceAttestationJwt.cs
- src/WalletFramework.Oid4Vc/ClientAttestation/WalletInstanceAttestationPopJwt.cs
- src/WalletFramework.Oid4Vc/DependencyInjection/ServiceCollectionExtensions.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Abstractions/IOid4VciClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/Abstractions/ITokenService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/DPop/Abstractions/IDPopHttpClient.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/DPop/Implementations/DPopHttpClient.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/Implementations/TokenService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/CredRequest/Implementations/CredentialRequestService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/IOid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtSigner.cs
- Adds support for Client Attestations during the Vci Flow
> Support Client Attestation in VCI Flow

- src/WalletFramework.Oid4Vc/DependencyInjection/ServiceCollectionExtensions.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/Abstractions/IVerifierKeyService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/Implementations/AuthorizationResponseEncryptionService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/Implementations/VerifierKeyService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/DcApi/Models/OpenId4VpDcApiHandover.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/DcApi/Models/OpenId4VpDcApiHandoverInfo.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/DcApi/Models/Origin.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Jwk/JwkFun.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/PresentationService.cs
VP Draft 29 introduces a specific SessionTranscript structure for mDoc presentation over DC-API. This PR updates the Framework to adopt that new structure when using DC-API.
- Use new SessionTranscript structure for MDoc DC-API
> [VP Draft 29] Implement new MDoc SessionTranscript for DC-API

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/RequestObject.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/AuthorizationRequestService.cs
- Adds validation for the client_id_prefix redirect_uri to ensure that the client_id matches the response_uri for security reasons
> Add client_id_prefix validation for redirect_uri

- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Errors/AuthFlowSessionCodeError.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Models/AuthFlowSessionCode.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Models/AuthFlowSessionState.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Models/IssuanceSession.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- Improves the IssuanceSession type by adding a Validation to the signature to ensure proper error handling
- Adds a AuthFlowSessionCode
> Improves IssuanceSession type
