openwallet-foundation-labs/wallet-framework-dotnet

- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/DefaultOid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/OidPresentationRecord.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpRecordService.cs
- src/Hyperledger.Aries/Features/SdJwt/Models/Records/SdJwtRecord.cs
- src/Hyperledger.Aries/Features/SdJwt/Services/SdJwtVcHolderService/DefaultSdJwtVcHolderService.cs
- src/Hyperledger.Aries/Storage/DefaultWalletRecordService.cs
- src/Hyperledger.Aries/Storage/Records/RecordBase.cs
Mainly moved some Properties of the SdJwt and Presentation-Records to Tags so it can be used in SearchQuerys. 
Also moved RecordVersion to Tags, because this could become useful for migration purposes in the future.
- See above
-
-
**Fixes**: /
> Adjust record versioning and tags

- .github/workflows/publish-nuget.yaml
This PR adds an authorize job to the pipeline which requires trusted Maintainers to approve a pipeline run whenever a pull request from a fork is introduced. This way, upon approval the pipeline can use the nuget API secret and publish new builds because of the pull_request_target trigger without introducing security vulnerabilities.
- publish-nuget.yaml
> Add support for fork PRs

- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/AuthorizationRequest.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Models/RequestObject.cs
- src/Hyperledger.Aries/Features/OpenID4VC/Vp/Services/Oid4VpHaipClient.cs
- src/Hyperledger.Aries/IsExternalInit.cs
Exposes the certificate of the request object so that the framework consumer can view it.
> Expose request object certificate in authorization request

- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/Authorization/TokenRequest.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Models/CredentialOffer/GrantTypes/PreAuthorizedCode.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/IOid4VciClientService.cs
- src/Hyperledger.Aries/Features/OpenID4VC/VCI/Services/Oid4VciClientService/Oid4VciClientService.cs
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Vci/Services/Oid4VciClientServiceTests.cs
This PR reintroduces the userPin from the Oid4Vci draft 12. Now the framework can handle tx_codes and userPins whatever the issuer chooses to use.
> add userPin

- src/Hyperledger.Aries/Features/OpenID4VC/KeyStore/Services/IKeyStore.cs
- src/Hyperledger.Aries/Features/SdJwt/Services/SdJwtVcHolderService/DefaultSdJwtVcHolderService.cs
- src/Hyperledger.Aries/Hyperledger.Aries.csproj
- test/Hyperledger.Aries.Tests/Features/OpenId4Vc/Vci/Services/Oid4VciClientServiceTests.cs
- test/Hyperledger.Aries.Tests/Features/SdJwt/SdJwtVcHolderTests.cs
- test/Hyperledger.Aries.Tests/Integration/Oid4VpClientServiceTests.cs
This PR adjust the Interface of GenerateKbProofOfPossessionAsync and the flow during the creation process of the presentation format of the SdJwt which allows the wallet to add the sd_hash field to the KbJwt.
> Add sd_hash field to KbJwt

- src/Hyperledger.Aries/Storage/DefaultWalletRecordService.cs
- src/Hyperledger.Aries/Storage/IWalletRecordService.cs
- src/WalletFramework.MdocVc/MdocRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Implementations/AuthFlowSessionStorage.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/AuthFlow/Records/AuthFlowSessionRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/MdocStorage.cs
- test/Hyperledger.Aries.Tests/Routing/RoutingInboxHandlerTests.cs
- test/WalletFramework.MdocVc.Tests/MdocRecordTests.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vci/AuthFlow/AuthFlowSessionRecordTests.cs
Remove NewtonSoft dependency from IWalletRecordService
> refactor persistence

- src/WalletFramework.MdocLib/IssuerSigned.cs
- src/WalletFramework.MdocLib/Mdoc.cs
- src/WalletFramework.MdocVc/MdocRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Abstractions/IOid4VciClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/DPop/Implementations/DPopHttpClient.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/DPop/Models/DPopToken.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Authorization/Models/OAuthToken.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/CredResponse/Mdoc/EncodedMdoc.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/ISdJwtVcHolderService.cs
- src/WalletFramework.SdJwtVc/Services/SdJwtVcHolderService/SdJwtVcHolderService.cs
- test/WalletFramework.Integration.Tests/WalletFramework.Integration.Tests/Oid4Vp/Oid4VpClientServiceTests.cs
- Adds a method to start the Authentication process of the Auth Code Flow by the wallet
- Adds a workaround for MDoc to allow malformed MDocs for the time being
> Add wallet initiated Auth Flow

- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/SdJwtRecordExtensions.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Models/Metadata/Credential/Attributes/OidClaim.cs
- src/WalletFramework.SdJwtVc/Models/Credential/Attributes/ClaimMetadata.cs
- This PR adds support for nested Claims
> support nested claims

- src/WalletFramework.Core/Base64Url/Base64UrlString.cs
- src/WalletFramework.Core/WalletFramework.Core.csproj
- src/WalletFramework.MdocLib/Mdoc.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/EncryptedAuthorizationResponse.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Jwk/JwkFun.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationResponse.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientJwksConverter.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientMetadata.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpHaipClient.cs
- src/WalletFramework.Oid4Vc/WalletFramework.Oid4Vc.csproj
This PR implements the functionality to encrypt the authorization response in case the response mode is direct-post.jwt
> Encrypted Authorization response

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientMetadata.cs
- This PR adds JsonIgnore to the JWks in ClientMetadata to fix its serialization.
> Fix Serialization of Client Metadata

- src/WalletFramework.SdJwtVc/WalletFramework.SdJwtVc.csproj
- This PR bumps the version of the SD-JWT lib which introduces a bugfix for SD-JWTs without the _sd_alg property if it does do not offer disclosures.
> Fix disclosureless Sd-Jwt

- global.json
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
Use the Auth Server Url referenced in the Cred Offer to find the appropriate Auth Server Url in the IssuerMetadata to fetch the Auth Server Metadata. If the Cred Offer references an Auth Server that is not part of the IssuerMetadata AuthServers the process should be aborted.
> Fix Auth Server Selection

- src/WalletFramework.Oid4Vc/Oid4Vci/CredConfiguration/Models/CredentialBackgroundImage.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/CredConfiguration/Models/CredentialDisplay.cs
- This PR adds the BackgroundImage property
> Add Background Image

- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/PexService.cs
This PR fixes a bug where the PexService returns invalid matching credentials when the selected JToken is an JObject or JArray instead of a required JValue.
-
-
-
**Fixes**: #
> fix pexservice

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/AuthorizationRequest.cs
This PR removes the HAIP conformance check and aligns the WF to support OpenId4VP draft 22 (https://openid.net/specs/openid-4-verifiable-presentations-1_0.html)
-
-
-
**Fixes**: #
> improve haip check & align with Oid4Vp draft 22

- src/WalletFramework.MdocVc/MdocRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/CredRequest/Implementations/CredentialRequestService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/SdJwtRecordExtensions.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
- test/WalletFramework.Integration.Tests/WalletFramework.Integration.Tests/Oid4Vp/Oid4VpClientServiceTests.cs
- Delete one time use credentials
> Delete one time use credentials

- Directory.Build.props
This PR bumps the Polly version to the latest stable.
-
-
-
**Fixes**: #
> bump polly from 7.2.1 to 8.5.0

- src/WalletFramework.Core/WalletFramework.Core.csproj
- src/WalletFramework.Oid4Vc/CredentialSet/CredentialSetService.cs
- src/WalletFramework.Oid4Vc/CredentialSet/Models/CredentialSetRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/PresentationDefinition.cs
- src/WalletFramework.Oid4Vc/SeviceCollectionExtensions.cs
- src/WalletFramework.SdJwtVc/Models/Records/SdJwtRecord.cs
- src/WalletFramework.SdJwtVc/Models/StatusList/Status.cs
- src/WalletFramework.SdJwtVc/Services/IStatusListService.cs
- src/WalletFramework.SdJwtVc/Services/StatusListService.cs
- src/WalletFramework.SdJwtVc/Services/VctMetadataService.cs
- test/WalletFramework.SdJwtVc.Tests/SdJwtVcHolderServiceTests.cs
- test/WalletFramework.SdJwtVc.Tests/StatusListTests.cs
- This PR adds the status list to SD-JWT credentials
> add status list support

- src/WalletFramework.Oid4Vc/CredentialSet/Models/CredentialSetRecord.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
This PR adds the Issuer Id to the CredentialSetRecord when an mDoc credential is issued
> Add Issuer Id to CredentialSetRecord for mDoc

- .github/workflows/publish-nuget.yaml
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientMetadata.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/Formats.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/MDocFormat.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/SdJwtFormat.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/InputDescriptor.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/PresentationDefinition.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/IPexService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/PexService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/IOid4VpHaipClient.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/Services/Oid4VpHaipClientTests.cs
- test/WalletFramework.Oid4Vc.Tests/PresentationExchange/Models/Can_Create_Presentation_Submission.json
- test/WalletFramework.Oid4Vc.Tests/PresentationExchange/Services/PexServiceTests.cs
> init vp_format support

- src/WalletFramework.Core/X509/X509CertificateExtensions.cs
This PR extends the selection of root certificates in the x509 chain of the x5c header.
> Extend the selection of Root Certificates in x509Chain

- src/WalletFramework.Oid4Vc/Oid4Vp/AuthResponse/Encryption/EncryptedAuthorizationResponse.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/ClientMetadata.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/AuthResponse/Encryption/EncryptedAuthorizationResponseTests.cs
- Make use of state in Encrypted Auth Response
- Use requested encoding from ClientMetadata for Encrypted Auth Response
> Fix Encrypted Authorization Response

- src/WalletFramework.Oid4Vc/Oid4Vp/Dcql/Services/DcqlService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Dcql/Services/IDcqlService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Models/PresentationMap.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/IPexService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Services/PexService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/IOid4VpHaipClient.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpHaipClient.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/PresentationExchange/Services/PexServiceTests.cs
This PR decouples transaction data from PEX as this led to exceptions when using DCQL queries.
A PresentationMap type is also introduced, which replaces a frequently used Tuple.
-
-
-
**Fixes**: #
> Decouple transaction data from PEX

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
This PR prevents the deletion of the last batch credential instance, because there is currently no way implemented to receive a new batch of credential instances.
-
-
-
**Fixes**: #
> prevent deletion of last batch credential

- src/WalletFramework.Oid4Vc/Oid4Vp/Extensions/JwtSecurityTokenExtensions.cs
This PR adds ES384 support for the Signature validation of the RequestObject.
> Add ES384 support for RequestObject

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/Oid4VpClientService.cs
- Fix the syntax of the value used for the aud claim in the KB-JWT (use <client_id_scheme>:<client_id> instead of <client_id>)
> Fix aud claim value in KB-JWT

- src/WalletFramework.Oid4Vc/Oid4Vp/PresentationExchange/Models/InputDescriptor.cs
- Also use the id of the InputDescriptor to extract the requested docType of a presentation request.
> also use the id from the input descriptor to extract the docType

- src/WalletFramework.Oid4Vc/Oid4Vci/CredOffer/GrantTypes/PreAuthorizedCode.cs
- src/WalletFramework.Oid4Vc/Oid4Vci/Implementations/Oid4VciClientService.cs
- Use the authServer that is specific in the CredentialOffer
> Use AuthServer requested in the CredentialOffer

- src/WalletFramework.Oid4Vc/Oid4Vp/Dcql/CredentialQueries/CredentialQuery.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/Dcql/DcqlFun.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/Dcql/CredentialSets/CredentialSetTests.cs
- test/WalletFramework.Oid4Vc.Tests/Oid4Vp/Dcql/Samples/DcqlSamples.cs
This PR tracks credentials that are only alternatives in the DCQL queries and therefore stops handling them as missing credentials as they are not relevant to answer the proof.
> Fix the DCQL missing credential filtering

- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataType.cs
- test/WalletFramework.Oid4Vc.Tests/QCertCreation/QCertCreationTests.cs
- test/WalletFramework.Oid4Vc.Tests/QCertCreation/Samples/QCertTransactionDataSamples.cs
- test/WalletFramework.Oid4Vc.Tests/Signatures/Samples/SignatureTransactionDataSamples.cs
- test/WalletFramework.Oid4Vc.Tests/Signatures/SignatureTests.cs
- Add transaction data _qes_ and _qcert acceptance_ types for csc spec
- Add appropriate unit tests
> Add csc transaction data types and unit tests

- src/WalletFramework.Oid4Vc/Qes/Authorization/DocumentDigest.cs
The CSC transaction data uses a _href_ property instead of the _documentLocation_uri_
> Add href property of CSC transaction data

- src/WalletFramework.Oid4Vc/Oid4Vp/Services/DcApiService.cs
TransactionData was missing in DC-API due to an implementation error. This PR fixed that.
**Fixes**: Missing TransactionData in DC-API
> Fix TransactionData in DC-API

- src/WalletFramework.Oid4Vc/Oid4Vp/DcApi/DcApiConstants.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/DcApi/Models/DcApiRequestItem.cs
For backwards compability reasons i added 'openid4vp' to the allowed protocols.
- 'openid4vp' will be handled the same 'opendi4vp-v1-unsigned'
-
-
> feature: Support Legacy Protocol 'openid4vp' for DC-API

- src/WalletFramework.Oid4Vc/Oid4Vp/Models/WalletMetadata.cs
- src/WalletFramework.Oid4Vc/Oid4Vp/TransactionDatas/TransactionDataFun.cs
- Fixes the WalletMetadata jsonString formatting
- Reverts the changes made to the tx_data linking when multiple credentials can be used
> Fix multiple credential tx data linking
